---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: imran
spec:
  profile:
    displayName: Imran Ahmad
  memberOf: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ali
  annotations:
    microsoft.com/user-oid: e2555667-ba77-49de-b5ec-d6bebafd8ec1
spec:
  profile:
    displayName: Ali
  memberOf: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bilal
  annotations:
    microsoft.com/user-oid: 045a6cc3-abe5-4ebf-abde-e912eff07ec5
spec:
  profile:
    displayName: Bilal
  memberOf: []

  